package com.nighthawkapps.lib.android.sdk.chat.darkirc

import com.nighthawkapps.lib.android.sdk.chat.DarkfiChatDefaults
import java.io.File

/**
 * Writes a [darkirc] TOML with absolute datastore paths under the app sandbox.
 *
 * Uses clearnet **`tcp+tls`** seeds so P2P can bootstrap without a local Tor SOCKS inside the daemon.
 */
internal object DarkircEmbeddedConfigGenerator {
    /** Default IRC bind for packaged darkirc (`127.0.0.1` + canonical port). */
    const val DEFAULT_IRC_LISTEN: String = "tcp://127.0.0.1:6667"

    fun buildToml(
        root: File,
        ircListenUri: String = DEFAULT_IRC_LISTEN,
        crypto: DarkircCryptoBundle = DarkircCryptoBundle(),
    ): String {
        val p2pRoot = File(root, "p2p").absolutePath.replace("\\", "\\\\")
        val sledDb = File(root, "darkirc_db").absolutePath.replace("\\", "\\\\")
        val replayDb = File(root, "replayed_darkirc_db").absolutePath.replace("\\", "\\\\")
        val autojoin =
            DarkfiChatDefaults.DEFAULT_PUBLIC_CHANNELS.joinToString(",\n ") { "\"$it\"" }
        val seeds =
            DarkfiChatDefaults.CLEARNET_SEEDS.joinToString(", ") { "\"$it\"" }
        val ircListenEscaped =
            ircListenUri
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")

        return """
            ## Generated by Nighthawk — paths are app-private.
            ## AGPL-3.0: DarkIRC is part of DarkFi (see docs/darkirc-embedded-android.md).

            irc_listen = "$ircListenEscaped"

            datastore = "$sledDb"
            replay_datastore = "$replayDb"

            autojoin = [
            $autojoin
            ]

            [rpc]
            rpc_listen = "tcp://127.0.0.1:26660"
            rpc_disabled_methods = ["p2p.get_info"]

            [net]
            magic_bytes = [251, 229, 199, 181]
            p2p_datastore = "$p2pRoot"
            hostlist = "$p2pRoot/p2p_hostlist.tsv"
            active_profiles = ["tcp+tls"]

            [net.profiles."tcp+tls"]
            seeds = [$seeds]
            """.trimIndent() +
            DarkircTomlCryptoSections.render(crypto).let { section ->
                if (section.isEmpty()) "" else "\n$section"
            } +
            "\n"
    }
}
