@file:Suppress("MagicNumber")

package com.nighthawkapps.lib.android.sdk.wallet.darkfid

import com.nighthawkapps.lib.android.sdk.wallet.DarkfiNetwork
import java.io.File

/**
 * Writes `darkfid_config.toml` for the packaged fullnode (upstream `bin/darkfid/darkfid_config.toml`).
 */
internal object DarkfidEmbeddedConfigGenerator {
    fun buildToml(
        root: File,
        network: DarkfiNetwork,
        p2pTransport: DarkfidP2pTransport = DarkfidP2pTransport.Clearnet,
    ): String {
        val dbPath = File(root, "chain_db").absolutePath.replace("\\", "\\\\")
        val p2pRoot = File(root, "p2p").absolutePath.replace("\\", "\\\\")
        val networkLabel = network.tomlLabel()
        val rpcPort = DarkfidChainDefaults.jsonRpcPort(network)
        val mgmtPort = DarkfidChainDefaults.managementRpcPort(network)
        val confirmationThreshold = DarkfidChainDefaults.confirmationThreshold(network)
        val netSection = netSectionFor(network, networkLabel, p2pRoot, p2pTransport)

        return """
            ## Generated by Nighthawk — embedded darkfid (upstream DrkPlugin expects loopback RPC).

            network = "$networkLabel"

            [network_config."$networkLabel"]
            database = "$dbPath"
            threshold = $confirmationThreshold
            max_forks = 32
            pow_target = 120
            skip_sync = false
            skip_fees = false

            [network_config."$networkLabel".rpc]
            rpc_listen = "tcp://127.0.0.1:$rpcPort"

            [network_config."$networkLabel".management_rpc]
            rpc_listen = "tcp://127.0.0.1:$mgmtPort"

            $netSection
            """.trimIndent() + "\n"
    }

    private fun netSectionFor(
        network: DarkfiNetwork,
        networkLabel: String,
        p2pRoot: String,
        p2pTransport: DarkfidP2pTransport,
    ): String {
        val magic = DarkfidChainDefaults.magicBytes(network).joinToString(", ")
        return when (p2pTransport) {
            DarkfidP2pTransport.Clearnet -> {
                val seeds =
                    DarkfidChainDefaults.clearnetP2pSeeds(network).joinToString(", ") { "\"$it\"" }
                """
                [network_config."$networkLabel".net]
                magic_bytes = [$magic]
                p2p_datastore = "$p2pRoot"
                hostlist = "$p2pRoot/p2p_hostlist.tsv"
                outbound_connections = 8
                localnet = false
                active_profiles = ["tcp+tls"]

                [network_config."$networkLabel".net.profiles."tcp+tls"]
                seeds = [$seeds]
                """.trimIndent()
            }

            is DarkfidP2pTransport.TorViaSocks5 -> {
                val proxy = "socks5://${p2pTransport.socksHost}:${p2pTransport.socksPort}"
                val socksHost = p2pTransport.socksHost
                val socksPort = p2pTransport.socksPort
                val seedLines =
                    buildList {
                        DarkfidChainDefaults.torOnionP2pSeeds(network).forEach { seed ->
                            val hostPort = seed.removePrefix("tor://")
                            add("\"socks5://$socksHost:$socksPort/$hostPort\"")
                        }
                        DarkfidChainDefaults.torTlsP2pSeeds(network).forEach { seed ->
                            val hostPort =
                                seed.removePrefix("tor+tls://").removePrefix("tcp+tls://")
                            add("\"socks5://$socksHost:$socksPort/$hostPort\"")
                        }
                    }
                val seeds = seedLines.joinToString(",\n ")
                """
                [network_config."$networkLabel".net]
                magic_bytes = [$magic]
                p2p_datastore = "$p2pRoot"
                hostlist = "$p2pRoot/p2p_hostlist.tsv"
                outbound_connections = 8
                localnet = false
                active_profiles = ["socks5"]
                tor_socks5_proxy = "$proxy"

                [network_config."$networkLabel".net.profiles."socks5"]
                seeds = [
                $seeds
                ]
                """.trimIndent()
            }
        }
    }

    private fun DarkfiNetwork.tomlLabel(): String =
        when (this) {
            DarkfiNetwork.Mainnet -> "mainnet"
            DarkfiNetwork.Testnet -> "testnet"
        }
}
