plugins {
    id("java")
}

val ktlint by configurations.creating

dependencies {
    // Fat jar (`all`) — runnable CLI (resolver: Maven Central under group com.pinterest.ktlint)
    ktlint("com.pinterest.ktlint:ktlint-cli:${project.property("KTLINT_VERSION")}:all")
}

tasks {
    val editorConfigFile = rootProject.file("tools/.editorconfig")
    val ktlintArgs =
        listOf(
            "**/src/**/*.kt",
            "!**/build/**",
            // UniFFI-generated Kotlin — regenerated by `uniffi-bindgen`; do not hand-edit or ktlint-fix.
            "!**/uniffi/**",
            "--editorconfig=${editorConfigFile.absolutePath}",
        )

    register("ktlint", org.gradle.api.tasks.JavaExec::class) {
        description = "Check code style with ktlint"
        classpath = ktlint
        mainClass.set("com.pinterest.ktlint.Main")
        jvmArgs("--add-opens", "java.base/java.lang=ALL-UNNAMED")
        args = ktlintArgs
    }

    register("ktlintFormat", org.gradle.api.tasks.JavaExec::class) {
        // https://github.com/pinterest/ktlint/issues/1195#issuecomment-1009027802
        jvmArgs("--add-opens", "java.base/java.lang=ALL-UNNAMED")

        description = "Apply code style formatting with ktlint"
        classpath = ktlint
        mainClass.set("com.pinterest.ktlint.Main")
        args = listOf("-F", "--ignore-autocorrect-failures") + ktlintArgs
    }
}

java {
    val javaVersion = JavaVersion.toVersion(project.property("ANDROID_JVM_TARGET").toString())
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}